test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: oblako
  username: oblako
  password: oblako

development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: oblako
  username: oblako
  password: oblako